# 1.This maps out your netplan interface framework applied at /etc/netplan/50-cloud-init.yaml.

network:
  version: 2 # 
  renderer: networkd
  ethernets:
    ens33: # Target ethernet hardware adapter name 
      dhcp4: no 
      addresses:
        - 192.168.192.xxx/24 # Replace 'xxx' with the exact server host IP 
      routes:
        - to: default 
          via: 192.168.192.2 # VMware NAT gateway IP 
      nameservers:
        addresses:
          - 8.8.8.8 # Google DNS Primary 
          - 8.8.4.4 # Google DNS Secondary 
