# File configured on the dedicated NFS Storage Server (192.168.192.143) at /etc/exports

/mnt/shared_uploads 192.168.192.0/24(rw,sync,no_subtree_check)

# Append this mount line to your web apps' local file system tables at /etc/fstab for automated boot orchestration.
192.168.192.143:/mnt/shared_uploads /var/www/html/uploads nfs defaults 0 0