# 1. Save this file at /etc/apache2/conf-available/remoteip.conf across both web hosts. 
# 2. Update on both web hosts to enable the mod_remoteip module and include this configuration file in the Apache2 main configuration.

<IfModule mod_remoteip.c>
    # Direct Apache to parse the X-Forwarded-For header added by Nginx 
    RemoteIPHeader X-Forwarded-For

    # Declare the frontdoor load balancer IP as a trusted internal proxy 
    RemoteIPInternalProxy 192.168.192.100
</IfModule>